apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxtest
spec:
  selector:
    matchLabels:
      name: nginxtest
  replicas: 2
  template:
    metadata:
      labels:
        name: nginxtest
    spec:

      containers:
      - name: my-nginx
        image: docker.io/jocatalin/kubernetes-bootcamp:v1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    run: nginx-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: nginxtest

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-r
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  # ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 8080