name: AKS

on:
  workflow_dispatch:
    inputs:
      run_terraform:
        description: "Type \"DEPLOY TERRAFORM\" to deploy Terraform"
        default: null
        required: false

  push:
    paths:
      - terraform/*.tf
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: 429f9634-504d-42be-9586-23ad4003f5ef
      ARM_CLIENT_SECRET: ydK8Q~ALdJfMne2kD6D2QeUfFiY~MPFsMA2PscnN
      ARM_SUBSCRIPTION_ID: 58299428-b94d-4171-8ae1-1aa5bccb1765
      ARM_TENANT_ID: 7d2c1f1a-ef24-4fed-84fe-2d915cb96792
      ARM_ACCESS_KEY: uDkqeDe1vo2KYudWS6n0997x2NCouC90ZWSnnu7rcuTIUICjNE5p3mhjConLOvIah27yhXFcicR3+AStpANDKg==

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: "terraform"
        
      - name: Terraform Format
        run: terraform fmt -check
        
      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          ARM_CLIENT_ID: 429f9634-504d-42be-9586-23ad4003f5ef
          ARM_CLIENT_SECRET: ydK8Q~ALdJfMne2kD6D2QeUfFiY~MPFsMA2PscnN
          ARM_SUBSCRIPTION_ID: 58299428-b94d-4171-8ae1-1aa5bccb1765
          ARM_TENANT_ID: 7d2c1f1a-ef24-4fed-84fe-2d915cb96792
      - name: Terraform Plan
        run: terraform plan
        working-directory: "terraform"
      
      - name: terraform apply 
        run: terraform apply -auto-approve
        working-directory: "terraform"
